name: 'Atlas DB switchover'
description: 'Promote primary on recovery region'

inputs:
  token_public:
    description: 'Atlas API token - public'
    required: true
  token_private:
    description: 'Atlas API token - private'
    required: true
  project:
    description: 'Atlas project hosting the services'
    required: true
  service_name:
    description: 'Atlas service name'
    required: true
  src_region:
    description: 'primary region'
    required: true
    default: 'WESTERN_EUROPE'
  dst_region:
    description: 'recovery region'
    required: true
    default: 'EUROPE_WEST_4'
  arb_region:
    description: 'arbitrary region'
    required: false
    default: 'EUROPE_NORTH_1'

outputs:
  myres:
    description: 'script output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_PROJECT: ${{ inputs.project }}
    INPUT_TOKEN_PUBLIC: ${{ inputs.token_public }}
    INPUT_TOKEN_PRIVATE: ${{ inputs.token_private }}
    INPUT_SERVICE: ${{ inputs.service_name }}
    INPUT_SRC_REGION: ${{ inputs.src_region }}
    INPUT_DST_REGION: ${{ inputs.dst_region }}
    INPUT_ARB_REGION: ${{ inputs.arb_region }}

